//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viselka.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Viselka.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АБАЖУР
        ///АБАЗИНЕЦ
        ///АБАЗИНКА
        ///АББАТ
        ///АББАТИСА
        ///АББАТСТВО
        ///АББРЕВИАТУРА
        ///АБЕРРАЦИЯ
        ///АБЗАЦ
        ///АБИССИНЕЦ
        ///АБИССИНКА
        ///АБИТУРИЕНТ
        ///АБИТУРИЕНТКА
        ///АБОНЕМЕНТ
        ///АБОНЕНТ
        ///АБОНЕНТКА
        ///АБОРДАЖ
        ///АБОРИГЕН
        ///АБОРИГЕНКА
        ///АБОРТ
        ///АБОРТИВНОСТЬ
        ///АБРАЗИВ
        ///АБРАКАДАБРА
        ///АБРЕК
        ///АБРИКОС
        ///АБРИС
        ///АБСЕНТЕИЗМ
        ///АБСОЛЮТ
        ///АБСОЛЮТИЗМ
        ///АБСОЛЮТНОСТЬ
        ///АБСТРАКТНОСТЬ
        ///АБСТРАКЦИОНИЗМ
        ///АБСТРАКЦИОНИСТ
        ///АБСТРАКЦИОНИСТКА
        ///АБСТРАКЦИЯ
        ///АБСУРД
        ///АБСУРДНОСТЬ
        ///АБСЦЕСС
        ///АБХАЗ
        ///АБХАЗЕЦ
        ///АБХАЗКА
        ///АВАНГАРД
        ///АВАНГАРДИЗМ
        ///АВАНГАРДИСТ
        ///АВАНГАРДИСТКА
        ///АВАНЗАЛ
        ///АВАНЛОЖА        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string slova {
            get {
                return ResourceManager.GetString("slova", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap step_1 {
            get {
                object obj = ResourceManager.GetObject("step_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap step_2 {
            get {
                object obj = ResourceManager.GetObject("step_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap step_3 {
            get {
                object obj = ResourceManager.GetObject("step_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap step_4 {
            get {
                object obj = ResourceManager.GetObject("step_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap step_5 {
            get {
                object obj = ResourceManager.GetObject("step_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap step_6 {
            get {
                object obj = ResourceManager.GetObject("step_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap step_7 {
            get {
                object obj = ResourceManager.GetObject("step_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
